### ISSUE TITLE
documentation adjustment for "YARN cluster address"

### ISSUE THREAD

**Issue by Tagar** [cerndb/Hadoop-Profiler#1]
From the root project page https://github.com/cerndb/Hadoop-Profiler

> One could also specify the YARN cluster address

Do you mean any IP address of any host? Or IP address of a host that runs YARN Resource Manager?

It would be great to adjust this so it's easier to follow. Thanks.

**Comment by JoeriHermans** [comment]
Hi @Tagar 

Thanks for the proof-reading! I actually mean the address of the host that runs the YARN Resource Manager. Like this:

>  http://[host]:[port]/ws/v1/cluster/nodes

So the hprofiler command will look like:

 `sh hprofiler.sh ... -c http://[host]:[port]/ws/v1/cluster/nodes ...`

I will update the README in order to clarify this. Thanks again!

**Edit:**  I updated the README for now, and added an alternative option (-h) for the YARN Resource Manager. I will rewrite the README so the complete process will be clear for everyone.

**Comment by Tagar** [comment]
Got it. Thanks a lot!
